<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyhdmEf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyhdmEf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyhdmEf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyhdmEf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYyhdmEf\App_KernelDevDebugContainer([
    'container.build_hash' => 'YyhdmEf',
    'container.build_id' => '4798ede3',
    'container.build_time' => 1678982011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyhdmEf');
